### Create a random tensor with shape (7, 7)

In [13]:
import torch

tensor1 = torch.rand(7, 7)
tensor1, tensor1.shape

(tensor([[0.7595, 0.5311, 0.6449, 0.7224, 0.4416, 0.3634, 0.8818],
         [0.9874, 0.7316, 0.2814, 0.0651, 0.0065, 0.5035, 0.3082],
         [0.3742, 0.4297, 0.9729, 0.9739, 0.4533, 0.3499, 0.7428],
         [0.4601, 0.0242, 0.6630, 0.9787, 0.1037, 0.3920, 0.6084],
         [0.0928, 0.0719, 0.8733, 0.3230, 0.7917, 0.5447, 0.6220],
         [0.1668, 0.3932, 0.8298, 0.7293, 0.3554, 0.5615, 0.8828],
         [0.0619, 0.8212, 0.3497, 0.3983, 0.7379, 0.0846, 0.4245]]),
 torch.Size([7, 7]))

### 3. Mat Mul another tensor shape 1, 7 need to transpose

In [4]:
tensor2 = torch.rand(1, 7)
tensor3 = torch.matmul(tensor1, tensor2.T)
tensor3, tensor3.shape

(tensor([[0.9726],
         [1.6222],
         [1.3188],
         [1.2157],
         [1.7078],
         [1.4842],
         [1.5909]]),
 torch.Size([7, 1]))

### 4. set the random seed to 0 and do 2 and 3 over again

In [8]:
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)
tensorA = torch.rand(7, 7)
torch.manual_seed(RANDOM_SEED)
tensorB = torch.rand(1, 7)

tensorC = torch.matmul(tensorA, tensorB.T)
tensorC, tensorC.shape

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

### 5. set GPU random seed to `1234`

In [9]:
RANDOM_SEED = 1234 if torch.cuda.is_available() else 0


### 6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed)

In [15]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensors on GPU
tensor_1 = torch.rand(2, 3).to(device)
tensor_2 = torch.rand(2, 3).to(device)
tensor_1, tensor_2

Device: cpu


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]]))

In [16]:
tensor_3 = torch.matmul(tensor_1, tensor_2.T)
tensor_3, tensor_3.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]]),
 torch.Size([2, 2]))

In [19]:
max = torch.max(tensor_3)
min = torch.min(tensor_3)

max, min

(tensor(0.5617), tensor(0.3647))

In [21]:
arg_max = torch.argmax(tensor_3)
arg_min = torch.argmin(tensor_3)

arg_max, arg_min

(tensor(3), tensor(0))

In [23]:
# Set seed 
torch.manual_seed(7)

# Create random tensor
X = torch.rand(1, 1, 1, 10)

# Removes single dimensions
Y = torch.squeeze(X)

print(X, X.shape)
print(Y, Y.shape)

tensor([[[[0.0290, 0.4019, 0.2598, 0.3666, 0.0583, 0.7006, 0.0518, 0.4681,
           0.6738, 0.3315]]]]) torch.Size([1, 1, 1, 10])
tensor([0.0290, 0.4019, 0.2598, 0.3666, 0.0583, 0.7006, 0.0518, 0.4681, 0.6738,
        0.3315]) torch.Size([10])
